#import "../../templates/templater.typ": *

= Volumes by cylindrical shells
Sometimes washers force us to rewrite everything in a clumsy way. Shells let us keep the original variable and picture thin hollow cylinders instead.

#definition("Shell Method")[
  When a region is rotated about an axis, a vertical strip can create a cylindrical shell.
  Its volume is approximately
  $ Delta V approx 2 pi ("radius")("height")("thickness") $

  So in the limit,
  $ V = 2 pi integral_a^b ("radius")("height") d x $
]

#note("Why shells are visual")[
  You should imagine wrapping a thin rectangle around the axis. The width becomes thickness, the height stays height, and the distance from the axis becomes radius. Unrolling the shell gives a flat slab of dimensions $2 pi r times h times d x$. That is where the formula comes from.
]

#canvas.cartesian-canvas(
  size: (8, 5),
  x-domain: (-2.6, 2.6),
  y-domain: (-0.5, 4.5),
  graph.graph(x => 2 * x, domain: (0, 2.1), label: $y = 2x$),
  graph.graph(x => x * x, domain: (0, 2.1), label: $y = x^2$),
  shape.segment(graph.point(1.3, 1.69), graph.point(1.3, 2.6), style: (stroke: gray)),
  shape.segment(graph.point(-1.3, 1.69), graph.point(-1.3, 2.6), style: (stroke: gray)),
  shape.segment(graph.point(0, -0.3), graph.point(0, 4.3), style: (stroke: gray)),
)

#example("Using Shells on the Same Region")[
  Rotate the region between
  $ y = 2x $
  and
  $ y = x^2 $
  on $[0,2]$ about the $y$-axis. Find the volume.
  #solution("")[
    A shell at position $x$ has
    - radius $x$
    - height $2x - x^2$
    The two gray strips in the picture are the same strip seen twice : once at $x$, once swung around to $-x$ mid-rotation.

    Therefore
    $ V = 2 pi integral_0^2 x(2x - x^2) d x $
    $ = 2 pi integral_0^2 (2x^2 - x^3) d x $
    $ = 2 pi [ 2x^3/3 - x^4/4 ]_0^2 $
    $ = 2 pi lr([ 16/3 - 4 ]) = 8 pi / 3 $
  ]
]

#example("A Shell Integral that Substitution Loves")[
  Find the volume of the solid generated by rotating the region bounded by
  $ y = sqrt(4 + x^2), quad y = 0, quad x = 0, quad x = 2 $
  about the $y$-axis.
  #solution("")[
    Washers would be painful here : solving $y = sqrt(4+x^2)$ for $x$ splits the solid into two different pieces. Shells keep everything in $x$.

    A shell at position $x$ has radius $x$ and height $sqrt(4+x^2)$, so
    $ V = 2 pi integral_0^2 x sqrt(4 + x^2) d x $

    Let
    $ u = 4 + x^2 $
    Then
    $ d u = 2x d x $
    and the bounds become $u = 4$ to $u = 8$ :
    $ V = pi integral_4^8 sqrt(u) d u = pi lr([ 2/3 u^(3/2) ])_4^8 $
    $ = (2pi)/3 lr([ 8^(3/2) - 4^(3/2) ]) = (2pi)/3 (16 sqrt(2) - 8) $

    So
    $ V = (16 pi)/3 (2 sqrt(2) - 1) $
  ]
]

#note("Washers or shells? How to decide")[
  Ask one question : is your slicing variable *parallel* or *perpendicular* to the axis of rotation?
  - Strip parallel to the axis $->$ it wraps around $->$ *shell*.
  - Strip perpendicular to the axis $->$ it spins in place $->$ *disk or washer*.
  Then pick whichever choice lets you describe the curves without solving for the inverse function.
]
